### PR TITLE
Ruby on Rails capstone project - Budget app

### PR DESCRIPTION
**Pull request by Mar12358**
### Added features:
- Features Video Presentation [here](https://www.loom.com/share/b8cad82f791f4e4a9d9aaac5a5e37769?sid=93377323-799a-44b3-9327-9ac9f6cbe226).
- The project is [deployed here](https://transactions-app-rngx.onrender.com/).
  > Test it with some existing examples, and feel free to add your owns:
  > Email: marting@gmail.com
  > Password: 123456

- [Design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) followed.

> NOTE: In these design guidelines there are several UIs that are not needed for this project; also, some pages are not given a design and were created following the design guidelines of the other pages.

#### Interactions
- Splash screen
  - A simple page with the name of the app that links to the sign-up and log in pages.
image

- Sign up and log in pages
  - The is be able to register in the app with name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can only access the Splash screen.
image
image

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "Add a new category" at the bottom that brings the user to the page to create a new category.
image

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.
image

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.
image

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
image

#### Testing requirements
- Unit and integration tests created.
image

### CODE REVIEW

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @Mar12358 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that have wrong workflow. Please make sure that use the correct workflow (Gitflow), you should create the PR and compare that feature branch with the development branch and not PR is created from development to main.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by binhussen — CHANGES_REQUESTED** [review]
Hi @Mar12358 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that have wrong workflow. Please make sure that use the correct workflow (Gitflow), you should create the PR and compare that feature branch with the development branch and not PR is created from development to main.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Mar12358** [comment]
Hi @binhussen. @Owusu-Desmond.
Thanks for your review. Kindly, please notice this PR is actually created from `dev` to `main`, as you can see:
image

However, I merged the deployment branch with the dev branch.
Thanks.

**Comment by binhussen** [comment]
@Mar12358 Kindly would you check how the [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) works  [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
Please be sure The PR has to be created from the `feature` branch to the `dev` branch as described earlier

**Pull request closed without merging**
